sudo: required
before_install:
  - sudo apt-get install ao
  - sudo apt-get install curl
  - sudo apt-get install mpg123

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Build steps
# Test
script:
  - mkdir build
  - cd build
  - cmake .. && make
